version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd nextjs-portfolio-2 && npm run dev"
    ports:
      - "3000:3000"
